-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-06-22 20:56:41 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE dowod_rejestracyjny (
    id_dowodu_rej     INTEGER NOT NULL,
    numer_dowodu_rej  VARCHAR2(7) NOT NULL,
    okres_waznosci    DATE,
    data_wydania      DATE NOT NULL,
    pojazd_id_pojazdu INTEGER NOT NULL
);

ALTER TABLE dowod_rejestracyjny ADD CONSTRAINT dowod_rejestracyjny_pk PRIMARY KEY ( id_dowodu_rej );

CREATE TABLE karta_pojazdu (
    id_karty_pojazdu    INTEGER NOT NULL,
    numer_karty_pojazdu VARCHAR2(12) NOT NULL,
    pojazd_id_pojazdu   INTEGER NOT NULL,
    data_wydania        DATE NOT NULL
);

ALTER TABLE karta_pojazdu ADD CONSTRAINT karta_pojazdu_pk PRIMARY KEY ( id_karty_pojazdu );

CREATE TABLE model_pojazdu (
    id_model_pojazdu            INTEGER NOT NULL,
    marka                       VARCHAR2(50) NOT NULL,
    nazwa                       VARCHAR2(30) NOT NULL,
    typ                         VARCHAR2(50),
    maks_masa                   INTEGER,
    dopuszczalna_masa           INTEGER NOT NULL,
    dopuszczalna_masa_zesp      INTEGER,
    dopuszczalna_ladownosc      INTEGER,
    najwiekszy_nacisk           INTEGER,
    masa_wlasna_pojazdu         INTEGER NOT NULL,
    kategoria_pojazdu           VARCHAR2(50),
    numer_swiadectwa_homo       VARCHAR2(50),
    liczba_osi                  INTEGER NOT NULL,
    maks_masa_przyczepy_z_ham   INTEGER,
    mask_masa_przyczepy_bez_ham INTEGER,
    pojemnosc_silnika           NUMBER(10, 2) NOT NULL,
    maks_moc_silnika            NUMBER(10, 2) NOT NULL,
    rodzaj_paliwa               VARCHAR2(1) NOT NULL,
    stosunek_mocy               NUMBER(10, 2),
    liczba_miejsc_siedzacych    INTEGER NOT NULL,
    liczba_miejsc_stojacych     INTEGER,
    rodzaj                      VARCHAR2(50) NOT NULL
);

ALTER TABLE model_pojazdu ADD CONSTRAINT model_pojazdu_pk PRIMARY KEY ( id_model_pojazdu );

CREATE TABLE pojazd (
    id_pojazdu                     INTEGER NOT NULL,
    data_pierwszej_rejestracji     DATE NOT NULL,
    rok_produkcji                  DATE NOT NULL,
    nr_vin                         VARCHAR2(17) NOT NULL,
    przeznaczenie_pojazdu          VARCHAR2(100),
    model_pojazdu_id_model_pojazdu INTEGER NOT NULL
);

ALTER TABLE pojazd ADD CONSTRAINT pojazd_pk PRIMARY KEY ( id_pojazdu );

CREATE TABLE satatus_dowodu (
    id_statusu_dowodu                 INTEGER NOT NULL,
    data_zmiany_statusu               DATE NOT NULL,
    status_dowodu                     VARCHAR2(20) NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    dowod_rejestracyjny_id_dowodu_rej INTEGER NOT NULL
);

ALTER TABLE satatus_dowodu ADD CONSTRAINT satatus_dowodu_pk PRIMARY KEY ( id_statusu_dowodu );

CREATE TABLE wlasciciel (
    id_wlasciciela   INTEGER NOT NULL,
    imie             VARCHAR2(50) NOT NULL,
    nazwisko         VARCHAR2(50) NOT NULL,
    pesel            VARCHAR2(11) NOT NULL,
    wojewodztwo      VARCHAR2(11) NOT NULL,
    powiat           VARCHAR2(30) NOT NULL,
    gmina            VARCHAR2(30) NOT NULL,
    ulica            VARCHAR2(30) NOT NULL,
    numer_domu       INTEGER NOT NULL,
    numer_mieszkania INTEGER
);

ALTER TABLE wlasciciel ADD CONSTRAINT wlasciciel_pk PRIMARY KEY ( id_wlasciciela );

CREATE TABLE wlasciciel_pojazd (
    wlasciciel_pojazd_id      INTEGER NOT NULL,
    data_od                   DATE NOT NULL,
    data_do                   DATE,
    wlasciciel_id_wlasciciela INTEGER NOT NULL,
    pojazd_id_pojazdu         INTEGER NOT NULL
);

ALTER TABLE wlasciciel_pojazd ADD CONSTRAINT wlasciciel_pojazd_pk PRIMARY KEY ( wlasciciel_pojazd_id );

CREATE TABLE zdarzenie_kradziezy (
    id_zdarzenia_kradziezy INTEGER NOT NULL,
    data_zdarzenia         DATE NOT NULL,
    status_kradziezy       VARCHAR2(20) NOT NULL,
    pojazd_id_pojazdu      INTEGER NOT NULL
);

ALTER TABLE zdarzenie_kradziezy ADD CONSTRAINT zdarzenie_kradziezy_pk PRIMARY KEY ( id_zdarzenia_kradziezy );

ALTER TABLE dowod_rejestracyjny
    ADD CONSTRAINT dowod_rejestracyjny_pojazd_fk FOREIGN KEY ( pojazd_id_pojazdu )
        REFERENCES pojazd ( id_pojazdu );

ALTER TABLE karta_pojazdu
    ADD CONSTRAINT karta_pojazdu_pojazd_fk FOREIGN KEY ( pojazd_id_pojazdu )
        REFERENCES pojazd ( id_pojazdu );

ALTER TABLE pojazd
    ADD CONSTRAINT pojazd_model_pojazdu_fk FOREIGN KEY ( model_pojazdu_id_model_pojazdu )
        REFERENCES model_pojazdu ( id_model_pojazdu );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE satatus_dowodu
    ADD CONSTRAINT satatus_dowodu_dowod_rejestracyjny_fk FOREIGN KEY ( dowod_rejestracyjny_id_dowodu_rej )
        REFERENCES dowod_rejestracyjny ( id_dowodu_rej );

ALTER TABLE wlasciciel_pojazd
    ADD CONSTRAINT wlasciciel_pojazd_pojazd_fk FOREIGN KEY ( pojazd_id_pojazdu )
        REFERENCES pojazd ( id_pojazdu );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE wlasciciel_pojazd
    ADD CONSTRAINT wlasciciel_pojazd_wlasciciel_fk FOREIGN KEY ( wlasciciel_id_wlasciciela )
        REFERENCES wlasciciel ( id_wlasciciela );

ALTER TABLE zdarzenie_kradziezy
    ADD CONSTRAINT zdarzenie_kradziezy_pojazd_fk FOREIGN KEY ( pojazd_id_pojazdu )
        REFERENCES pojazd ( id_pojazdu );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   3
-- WARNINGS                                 0
